### PR TITLE
Add missing fstream include

### PR DESCRIPTION
**Pull request by miquelmassot**

### CODE REVIEW

**Comment by miquelmassot** [comment]
FYI the compilation error has nothing to do with the current PR:

```
g2o_qglviewer.cpp:81:25: error: invalid user-defined conversion from ‘Qt::WindowFlags’ {aka ‘QFlags<Qt::WindowType>’} to ‘const QGLWidget*’ [-fpermissive]
```

**Comment by RainerKuemmerle** [comment]
> FYI the compilation error has nothing to do with the current PR:
> 
> ```
> g2o_qglviewer.cpp:81:25: error: invalid user-defined conversion 
> from 
> ‘Qt::WindowFlags’ {aka ‘QFlags<Qt::WindowType>’} 
> to 
> ‘const QGLWidget*’ [-fpermissive]
> ```

Thanks. I need to revisit this and setup CI for the pymem branch. I broke this by accident while trying to avoid a deprecation warning from libqglviewer.

**Comment by miquelmassot** [comment]
I am hitting a different error in my CI - could I get your eyes into this? 
https://github.com/miquelmassot/g2o-python/actions/runs/7101323340/job/19329185672#step:4:279

**Comment by RainerKuemmerle** [comment]
@miquelmassot I saw you changed CI on the master branch. Did it resolve the issue?
The above job did not install libeigen explicitly. The reshaped method got added in Eigen 3.4. I wanted to push a change to the pymem branch to reflect this min version requirement.

**Pull request merged**
