### PR TITLE
Feature: add support to EdgeSE3XYZPrior

### PR DESCRIPTION
**Pull request by TSC21**
This PR pretends to address #333. I am not really sure what functions are really required to be included on the prior and if the bellow are completely right, so this can be considered a WIP/RFC.

@RainerKuemmerle would you mind giving your input here?

Thanks in advance!

### CODE REVIEW

**Comment by TSC21** [comment]
@RainerKuemmerle friendly ping :) I think this is an important matter for many others who would like to use GPS data as priors in 3D graphslam. Thank you

**Comment by TSC21** [comment]
@RainerKuemmerle this was merged and I thank you for that. But I was also looking for your feedback on it and understand that all functions are correct. I am going to assume they are giving that you merged it without review and didn't do any change on my src code after.

**Comment by skasperski** [comment]
Hello,

I am trying to use this edge type, but I get an error when I add it to the solver, e.g. the addEdge() call in

	g2o::EdgeSE3XYZPrior* prior = new g2o::EdgeSE3XYZPrior();
	prior->vertices()[0] = mInt->optimizer.vertex(vertex);
	prior->setMeasurement(pos->getPosition().cast<double>());
	prior->setInformation(pos->getCovariance().inverse().cast<double>());	
	mInt->optimizer.addEdge(prior);

throws an std::bad_typeid. After some debugging, this seems to be caused by the _offsetParam, which is set to "0" and then never changed, from what I can see. Maybe I missed some necessary step upon creation of the edge?

Best regards,
Sebastian

**Comment by radeonwu** [comment]
Met the same "bad_typeid" error as skasperski, when using EdgeSE3Prior. Not sure if skasperski or anyone else already have the solution? any insights are also welcome. 
Best regards
Wu
> Hello,
> 
> I am trying to use this edge type, but I get an error when I add it to the solver, e.g. the addEdge() call in
> 
> ```
> g2o::EdgeSE3XYZPrior* prior = new g2o::EdgeSE3XYZPrior();
> prior->vertices()[0] = mInt->optimizer.vertex(vertex);
> prior->setMeasurement(pos->getPosition().cast<double>());
> prior->setInformation(pos->getCovariance().inverse().cast<double>());	
> mInt->optimizer.addEdge(prior);
> ```
> 
> throws an std::bad_typeid. After some debugging, this seems to be caused by the _offsetParam, which is set to "0" and then never changed, from what I can see. Maybe I missed some necessary step upon creation of the edge?
> 
> Best regards,
> Sebastian

**Comment by ShougangShen** [comment]
> Met the same "bad_typeid" error as skasperski, when using EdgeSE3Prior. Not sure if skasperski or anyone else already have the solution? any insights are also welcome.
> Best regards
> Wu
> 
> > Hello,
> > I am trying to use this edge type, but I get an error when I add it to the solver, e.g. the addEdge() call in
> > ```
> > g2o::EdgeSE3XYZPrior* prior = new g2o::EdgeSE3XYZPrior();
> > prior->vertices()[0] = mInt->optimizer.vertex(vertex);
> > prior->setMeasurement(pos->getPosition().cast<double>());
> > prior->setInformation(pos->getCovariance().inverse().cast<double>());	
> > mInt->optimizer.addEdge(prior);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > throws an std::bad_typeid. After some debugging, this seems to be caused by the _offsetParam, which is set to "0" and then never changed, from what I can see. Maybe I missed some necessary step upon creation of the edge?
> > Best regards,
> > Sebastian

I have met the same problem! Has anyone solved the problem? Thanks!

**Comment by skasperski** [comment]
I ended up using my own implementation for a position prior to add GPS constraints to g2o.

https://github.com/dfki-ric/slam3d/blob/master/slam3d/solver/g2o/edge_position_prior.h

**Pull request merged**
